In [1]:
%matplotlib inline
import pandas as pd

In [2]:
cast = pd.read_csv("D:/Sudip Files and Folders/Top Mentor/Python/Mar 1/cast.csv")
cast.head()

,title,year,name,type,character,n
0,Closet Monster,2015.0,Buffy #1,actor,Buffy 4,NaN
1,Suuri illusioni,1985.0,Homo $,actor,Guests,22.0
2,Battle of the Sexes,2017.0,$hutter,actor,Bobby Riggs Fan,10.0
3,Secret in Their Eyes,2015.0,$hutter,actor,2002 Dodger Fan,NaN
4,Steve Jobs,2015.0,$hutter,actor,1988 Opera House Patron,NaN

### How many movies are listed in the cast dataframe?

In [3]:
print("Number of Movies listed in the file is:",cast['title'].nunique())

Number of Movies listed in the file is: 166670

In [4]:
cast.shape

(2159949, 6)

### What are the earliest two films listed in the titles dataframe?

In [5]:
#First Solution
x=cast[['title','year']].sort_values('year').drop_duplicates().head(2)['title'].unique()

In [6]:
print(f'The two earliest film in the cast dataframe are: "{x[0]}" and "{x[1]}"')

The two earliest film in the cast dataframe are: "Miss Jerry" and "Soldiers of the Cross"

In [7]:
## Second alternative solution using nsmallest:
first2=cast[['title','year']].drop_duplicates("title").nsmallest(2,'year')['title'].unique()
print("The two earliest films in the cast dataframe are: 1.",first2[0],"and 2.",first2[1])

The two earliest films in the cast dataframe are: 1. Miss Jerry and 2. Soldiers of the Cross

In [8]:
###Third Solution using set_index:
x_index=cast.set_index("year").sort_index().drop_duplicates("title").head(2)["title"].unique()
print("The two earliest films in the cast dataframe are: 1.",x_index[0],"and 2.",x_index[1])

The two earliest films in the cast dataframe are: 1. Miss Jerry and 2. Soldiers of the Cross

### How many movies have the title "Hamlet"?

In [9]:
%time
print(f'There are {(cast['title']=="Hamlet").sum()} number of movies having the title "Hamlet"')

CPU times: total: 0 ns
Wall time: 0 ns
There are 218 number of movies having the title "Hamlet"

In [10]:
## Second Alternative using set_index and .loc function
%time
h=cast.set_index("title").sort_index()
print(f'No of movies having title "Hamlet" is: {len(h.loc["Hamlet"])}')

CPU times: total: 0 ns
Wall time: 0 ns
No of movies having title "Hamlet" is: 218

### How many movies are titled "North by Northwest"?

In [11]:
print(f'There are {(cast['title']=="North by Northwest").sum()} number of movies having the title "North by Northwest"')

There are 81 number of movies having the title "North by Northwest"

In [12]:
## Using index function as earlier
print(f'No of movies having title "Hamlet" is: {len(h.loc["North by Northwest"])}')

No of movies having title "Hamlet" is: 81

### When was the first movie titled "Hamlet" made?

In [13]:
year1=cast[cast["title"]=="Hamlet"].sort_values('year').head(1)['year'].unique()
print(f'The first movie titled "Hamlet" was made on {year1[0]}')

The first movie titled "Hamlet" was made on 1910.0

In [14]:
cast[cast["title"]=="Hamlet"]["year"].min()

1910.0

In [15]:
cast[cast["title"]=="Hamlet"].sort_values("year").head(1)

          title    year               name   type character   n
1545289  Hamlet  1910.0  Jean Mounet-Sully  actor    Hamlet NaN

### List all of the "Treasure Island" movies from earliest to most recent.

In [16]:
list_all=cast[cast["title"]=="Treasure Island"].sort_values("year")
print("All moveis of 'Treasure Island' movies from earliest to most recent are: ", list_all)

All moveis of 'Treasure Island' movies from earliest to most recent are:                     title    year                  name   type  \
1291387  Treasure Island  1918.0          Elmo Lincoln  actor
830114   Treasure Island  1918.0        Charles Gorman  actor
840745   Treasure Island  1918.0             Joe Grant  actor
909157   Treasure Island  1918.0          Edwin Harley  actor
1946119  Treasure Island  1918.0         Lewis Sargent  actor
...                  ...     ...                   ...    ...
1959741  Treasure Island  1999.0        Richard Schave  actor
872384   Treasure Island  1999.0         Paul Gutrecht  actor
210668   Treasure Island  1999.0        Jonah Blechman  actor
1869989  Treasure Island  1999.0  Scot Thomas Robinson  actor
880460   Treasure Island  1999.0          Rio Hackford  actor

                       character     n
1291387          Prologue Player   NaN
830114           Prologue Player   NaN
840745   Undetermined child role   NaN
909157           Prologue Player   NaN
1946119                 Ben Gunn   5.0
...                          ...   ...
1959741                      Man  21.0
872384                  Some Guy  20.0
210668                  The Body   3.0
1869989                    Jimmy  11.0
880460                      Hans  23.0

[154 rows x 6 columns]

### How many movies were made in the year 1950?

In [17]:
print("Number of movies made in the year 1950 are:", cast[cast["year"]==1950]["title"].nunique())

Number of movies made in the year 1950 are: 884

### How many movies were made in the year 1960?

In [18]:
print("Number of Movies made in the year 1960 are:", cast[cast["year"]==1960]["title"].nunique())

Number of Movies made in the year 1960 are: 1050

### How many movies were made from 1950 through 1959?

In [19]:
print("Number of movies made during 1950 to 1959 are:", cast[(cast["year"]>=1950) & (cast["year"]<=1959)]["title"].nunique())

Number of movies made during 1950 to 1959 are: 9827

### In what years has a movie titled "Batman" been released?

In [20]:
batman=cast[cast["title"]=="Batman"].sort_values("year")["year"].min()
print("The movie titles 'Batman' was release on: ", batman)

The movie titles 'Batman' was release on:  1943.0

### How many roles were there in the movie "Inception"?

In [21]:
cast.head()

,title,year,name,type,character,n
0,Closet Monster,2015.0,Buffy #1,actor,Buffy 4,NaN
1,Suuri illusioni,1985.0,Homo $,actor,Guests,22.0
2,Battle of the Sexes,2017.0,$hutter,actor,Bobby Riggs Fan,10.0
3,Secret in Their Eyes,2015.0,$hutter,actor,2002 Dodger Fan,NaN
4,Steve Jobs,2015.0,$hutter,actor,1988 Opera House Patron,NaN

In [22]:
print("Number of Roles present in the movie 'Inception' are: ", cast[cast["title"]=="Inception"]["character"].nunique())

Number of Roles present in the movie 'Inception' are:  42

### How many roles in the movie "Inception" are NOT ranked by an "n" value?

In [23]:
print(f'{cast[cast["title"]=="Inception"]["n"].isnull().sum()} number of movies are NOT ranked by "n" value')

21 number of movies are NOT ranked by "n" value

### But how many roles in the movie "Inception" did receive an "n" value?

In [24]:
print(f'{cast[cast["title"]=="Inception"]["n"].notnull().sum()} number of movies are ranked by "n" value')

31 number of movies are ranked by "n" value

### Display the cast of "North by Northwest" in their correct "n"-value order, ignoring roles that did not earn a numeric "n" value.

In [25]:
northwest=cast[cast["title"]=="North by Northwest"].sort_values('n')
print("List of 'North by Northwest' movies sorted in ascending order and not containing null values for 'n':\n\n",northwest[northwest['n'].notnull()])

List of 'North by Northwest' movies sorted in ascending order and not containing null values for 'n':

                       title    year               name   type  \
840374   North by Northwest  1959.0         Cary Grant  actor
1404704  North by Northwest  1959.0        James Mason  actor
343701   North by Northwest  1959.0     Leo G. Carroll  actor
1634552  North by Northwest  1959.0        Philip Ober  actor
1229083  North by Northwest  1959.0      Martin Landau  actor
1746383  North by Northwest  1959.0       Edward Platt  actor
642085   North by Northwest  1959.0  Robert Ellenstein  actor
447893   North by Northwest  1959.0    Philip Coolidge  actor
1454363  North by Northwest  1959.0      Patrick McVey  actor
198496   North by Northwest  1959.0       Edward Binns  actor
1334726  North by Northwest  1959.0          Ken Lynch  actor

                           character     n
840374            Roger O. Thornhill   1.0
1404704              Phillip Vandamm   3.0
343701                 The Professor   5.0
1634552              Lester Townsend   7.0
1229083                      Leonard   8.0
1746383              Victor Larrabee  10.0
642085                         Licht  11.0
447893                     Dr. Cross  13.0
1454363               Sergeant Flamm  14.0
198496                Captain Junket  15.0
1334726  Charley - Chicago Policeman  16.0

### Display the entire cast, in "n"-order, of the 1972 film "Sleuth".

In [26]:
print("The movie - Sleuth of 1972 arranged in n-order is :", cast[(cast["year"]==1972)&(cast["title"]=="Sleuth")].sort_values('n'))

The movie - Sleuth of 1972 arranged in n-order is :           title    year                name   type  \
1644328  Sleuth  1972.0    Laurence Olivier  actor
314691   Sleuth  1972.0       Michael Caine  actor
360365   Sleuth  1972.0      Alec Cawthorne  actor
1412647  Sleuth  1972.0  John (II) Matthews  actor
1396572  Sleuth  1972.0        Teddy Martin  actor

                          character    n
1644328                 Andrew Wyke  1.0
314691                  Milo Tindle  2.0
360365            Inspector Doppler  3.0
1412647  Detective Sergeant Tarrant  4.0
1396572      Police Constable Higgs  6.0

In [27]:
##Alternative way using .loc:
s=cast.set_index(["title","year"])
s.loc["Sleuth"].loc[1972].sort_values("n")
print("The movie - Sleuth of 1972 arranged in n-order is :", s.loc["Sleuth"].loc[1972].sort_values("n"))

The movie - Sleuth of 1972 arranged in n-order is :                       name   type                   character    n
year
1972.0    Laurence Olivier  actor                 Andrew Wyke  1.0
1972.0       Michael Caine  actor                 Milo Tindle  2.0
1972.0      Alec Cawthorne  actor           Inspector Doppler  3.0
1972.0  John (II) Matthews  actor  Detective Sergeant Tarrant  4.0
1972.0        Teddy Martin  actor      Police Constable Higgs  6.0

### Now display the entire cast, in "n"-order, of the 2007 version of "Sleuth".

In [28]:
print("The movie - Sleuth of year - 2007 arranged in n-order is :" , s.loc["Sleuth"].loc[2007].sort_values("n"))

The movie - Sleuth of year - 2007 arranged in n-order is :                        name   type          character    n
year
2007.0        Michael Caine  actor             Andrew  1.0
2007.0             Jude Law  actor               Milo  2.0
2007.0        Harold Pinter  actor        Man on T.V.  3.0
2007.0      Kenneth Branagh  actor  Other Man on T.V.  NaN
2007.0  Alec (II) Cawthorne  actor  Inspector Doppler  NaN

### How many roles were credited in the silent 1921 version of Hamlet?

In [29]:
print("The number of roles credited in the silent 1921 version of Hamlet is:",cast[(cast["title"]=="Hamlet") & (cast["year"]==1921)]["character"].nunique())

The number of roles credited in the silent 1921 version of Hamlet is: 5

### How many roles were credited in Branagh’s 1996 Hamlet?

In [30]:
print("The number of roles credited in the silent 1996 version of Hamlet is:",cast[(cast["title"]=="Hamlet")&(cast["year"]==1996)]["character"].nunique())

The number of roles credited in the silent 1996 version of Hamlet is: 35

### How many "Hamlet" roles have been listed in all film credits through history?

In [31]:
print("The number of 'Hamlet' roles credited in all movies in the history are:",cast[cast["character"]=="Hamlet"]["name"].nunique())

The number of 'Hamlet' roles credited in all movies in the history are: 78

In [32]:
## Alternative Solution
cast[cast['character']=='Hamlet'].shape[0]

78

### How many people have played an "Ophelia"?

In [33]:
ophelia=cast[(cast["character"]=="Ophelia")&(cast["type"]=="actor")]["name"].nunique()
print(f'There are {ophelia} number of people have played "Ophelia"')

There are 7 number of people have played "Ophelia"

### How many people have played a role called "The Dude"?

In [34]:
dude=cast[(cast["character"]=="The Dude")&(cast["type"]=="actor")]["name"].nunique()
print(f'There are {dude} number of people who has played the role of "The Dude"')

There are 16 number of people who has played the role of "The Dude"

### How many people have played a role called "The Stranger"?

In [35]:
stranger=cast[cast["character"]=="The Stranger"]["name"].nunique()
print(f'There are {stranger} number of people who has played the role of "The Stranger"')

There are 173 number of people who has played the role of "The Stranger"

### How many roles has Sidney Poitier played throughout his career?

In [36]:
print("Number of roles played by Sidney Poitier is: ",cast[cast['name']=="Sidney Poitier"]['character'].nunique())

Number of roles played by Sidney Poitier is:  41

### How many roles has Judi Dench played?

In [37]:
print("The number of roles palyed by Judi Dench is:", cast[cast['name']=='Judi Dench']['character'].nunique())

The number of roles palyed by Judi Dench is: 0

### List the supporting roles (having n=2) played by Cary Grant in the 1940s, in order by year.

In [38]:
cast[(cast["name"]=="Cary Grant")&(cast["year"]>=1940)&(cast["year"]<1950)].sort_values("year")

,title,year,name,type,character,n
840399,The Philadelphia Story,1940.0,Cary Grant,actor,C. K. Dexter Haven,1.0
840397,The Howards of Virginia,1940.0,Cary Grant,actor,Matt Howard,1.0
840353,His Girl Friday,1940.0,Cary Grant,actor,Walter Burns,1.0
840371,My Favorite Wife,1940.0,Cary Grant,actor,Nick,2.0
840386,Suspicion,1941.0,Cary Grant,actor,Johnnie,1.0
840381,Penny Serenade,1941.0,Cary Grant,actor,Roger Adams,2.0
840401,The Talk of the Town,1942.0,Cary Grant,actor,Leopold Dilg,1.0
840377,Once Upon a Honeymoon,1942.0,Cary Grant,actor,Patrick 'Pat' O'Toole,1.0
840344,Destination Tokyo,1943.0,Cary Grant,actor,Capt. Cassidy,1.0
840369,Mr. Lucky,1943.0,Cary Grant,actor,Joe Adams,1.0
840370,Mr. Lucky,1943.0,Cary Grant,actor,Joe Bascopolous,1.0
840336,Arsenic and Old Lace,1944.0,Cary Grant,actor,Mortimer Brewster,1.0
840378,Once Upon a Time,1944.0,Cary Grant,actor,Jerry Flynn,1.0
840373,None But the Lonely Heart,1944.0,Cary Grant,actor,Ernie Mott,1.0
840351,George White's Scandals,1945.0,Cary Grant,actor,Cary Grant,NaN
840372,Night and Day,1946.0,Cary Grant,actor,Cole Porter,1.0
840375,Notorious,1946.0,Cary Grant,actor,Devlin,1.0
840415,Without Reservations,1946.0,Cary Grant,actor,Cary Grant,NaN
840393,The Bachelor and the Bobby-Soxer,1947.0,Cary Grant,actor,Dick Nugent,1.0
840394,The Bishop's Wife,1947.0,Cary Grant,actor,Dudley,1.0
840368,Mr. Blandings Builds His Dream House,1948.0,Cary Grant,actor,Jim Blandings,1.0
840348,Every Girl Should Be Married,1948.0,Cary Grant,actor,Dr. Madison Brown,1.0
840357,I Was a Male War Bride,1949.0,Cary Grant,actor,Captain Henri Rochard,1.0

In [44]:
cast[(cast["name"]=="Cary Grant")&(cast["year"]//10*10 == 1940)].sort_values("year")

,title,year,name,type,character,n
840399,The Philadelphia Story,1940.0,Cary Grant,actor,C. K. Dexter Haven,1.0
840397,The Howards of Virginia,1940.0,Cary Grant,actor,Matt Howard,1.0
840353,His Girl Friday,1940.0,Cary Grant,actor,Walter Burns,1.0
840371,My Favorite Wife,1940.0,Cary Grant,actor,Nick,2.0
840386,Suspicion,1941.0,Cary Grant,actor,Johnnie,1.0
840381,Penny Serenade,1941.0,Cary Grant,actor,Roger Adams,2.0
840401,The Talk of the Town,1942.0,Cary Grant,actor,Leopold Dilg,1.0
840377,Once Upon a Honeymoon,1942.0,Cary Grant,actor,Patrick 'Pat' O'Toole,1.0
840344,Destination Tokyo,1943.0,Cary Grant,actor,Capt. Cassidy,1.0
840369,Mr. Lucky,1943.0,Cary Grant,actor,Joe Adams,1.0
840370,Mr. Lucky,1943.0,Cary Grant,actor,Joe Bascopolous,1.0
840336,Arsenic and Old Lace,1944.0,Cary Grant,actor,Mortimer Brewster,1.0
840378,Once Upon a Time,1944.0,Cary Grant,actor,Jerry Flynn,1.0
840373,None But the Lonely Heart,1944.0,Cary Grant,actor,Ernie Mott,1.0
840351,George White's Scandals,1945.0,Cary Grant,actor,Cary Grant,NaN
840372,Night and Day,1946.0,Cary Grant,actor,Cole Porter,1.0
840375,Notorious,1946.0,Cary Grant,actor,Devlin,1.0
840415,Without Reservations,1946.0,Cary Grant,actor,Cary Grant,NaN
840393,The Bachelor and the Bobby-Soxer,1947.0,Cary Grant,actor,Dick Nugent,1.0
840394,The Bishop's Wife,1947.0,Cary Grant,actor,Dudley,1.0
840368,Mr. Blandings Builds His Dream House,1948.0,Cary Grant,actor,Jim Blandings,1.0
840348,Every Girl Should Be Married,1948.0,Cary Grant,actor,Dr. Madison Brown,1.0
840357,I Was a Male War Bride,1949.0,Cary Grant,actor,Captain Henri Rochard,1.0

### List the leading roles that Cary Grant played in the 1940s in order by year.

In [56]:
print("Leading Roles played by Cary Grant in the 1940s in order by year are:\n\n",cast[(cast["name"]=="Cary Grant") & (cast["year"]//10*10==1940)].sort_values("year"))

Leading Roles played by Cary Grant in the 1940s in order by year are:

                                        title    year        name   type  \
840399                The Philadelphia Story  1940.0  Cary Grant  actor
840397               The Howards of Virginia  1940.0  Cary Grant  actor
840353                       His Girl Friday  1940.0  Cary Grant  actor
840371                      My Favorite Wife  1940.0  Cary Grant  actor
840386                             Suspicion  1941.0  Cary Grant  actor
840381                        Penny Serenade  1941.0  Cary Grant  actor
840401                  The Talk of the Town  1942.0  Cary Grant  actor
840377                 Once Upon a Honeymoon  1942.0  Cary Grant  actor
840344                     Destination Tokyo  1943.0  Cary Grant  actor
840369                             Mr. Lucky  1943.0  Cary Grant  actor
840370                             Mr. Lucky  1943.0  Cary Grant  actor
840336                  Arsenic and Old Lace  1944.0  Cary Grant  actor
840378                      Once Upon a Time  1944.0  Cary Grant  actor
840373             None But the Lonely Heart  1944.0  Cary Grant  actor
840351               George White's Scandals  1945.0  Cary Grant  actor
840372                         Night and Day  1946.0  Cary Grant  actor
840375                             Notorious  1946.0  Cary Grant  actor
840415                  Without Reservations  1946.0  Cary Grant  actor
840393      The Bachelor and the Bobby-Soxer  1947.0  Cary Grant  actor
840394                     The Bishop's Wife  1947.0  Cary Grant  actor
840368  Mr. Blandings Builds His Dream House  1948.0  Cary Grant  actor
840348          Every Girl Should Be Married  1948.0  Cary Grant  actor
840357                I Was a Male War Bride  1949.0  Cary Grant  actor

                    character    n
840399     C. K. Dexter Haven  1.0
840397            Matt Howard  1.0
840353           Walter Burns  1.0
840371                   Nick  2.0
840386                Johnnie  1.0
840381            Roger Adams  2.0
840401           Leopold Dilg  1.0
840377  Patrick 'Pat' O'Toole  1.0
840344          Capt. Cassidy  1.0
840369              Joe Adams  1.0
840370        Joe Bascopolous  1.0
840336      Mortimer Brewster  1.0
840378            Jerry Flynn  1.0
840373             Ernie Mott  1.0
840351             Cary Grant  NaN
840372            Cole Porter  1.0
840375                 Devlin  1.0
840415             Cary Grant  NaN
840393            Dick Nugent  1.0
840394                 Dudley  1.0
840368          Jim Blandings  1.0
840348      Dr. Madison Brown  1.0
840357  Captain Henri Rochard  1.0

### How many roles were available for actors in the 1950s?

In [68]:
print("Total Roles available for actors in the 1950s is:", cast[(cast["type"]=="actor")&((cast["year"]//10*10)==1950)]["character"].nunique())

Total Roles available for actors in the 1950s is: 82039

### How many roles were available for actresses in the 1950s?

In [69]:
print("Number od roles available for actresses in the 1950s is:",cast[(cast["type"]=="actresses") & (cast["year"]//10*10)]["character"].nunique())

Number od roles available for actresses in the 1950s is: 0

### How many leading roles (n=1) were available from the beginning of film history through 1980?

In [74]:
print("Leading roles available from the beginning of film history through 1980 is:", cast[(cast['n']==1) & (cast["year"]<=1980)]['character'].nunique())

Leading roles available from the beginning of film history through 1980 is: 31217

### How many non-leading roles were available through from the beginning of film history through 1980?

In [75]:
print("Non-leading roles available from the beginning of film history through 1980 is:", cast[(cast['n']!=1) & (cast["year"]<=1980)]['character'].nunique())

Non-leading roles available from the beginning of film history through 1980 is: 364422

### How many roles through 1980 were minor enough that they did not warrant a numeric "n" rank?

In [83]:
print("Roles performed by minor from the beginning of film history through 1980 is:", cast[(cast["year"]<=1980) & (cast["n"].isnull())]["character"].nunique())

Roles performed by minor from the beginning of film history through 1980 is: 127649